security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Entity\Usuario:
            algorithm: auto

    role_hierarchy:
        ROLE_OPERADOR_EXTERNO_PRUEBAS: [ROLE_VISITANTE]
        ROLE_OPERADOR_EXTERNO: [ROLE_OPERADOR_EXTERNO_PRUEBAS, ROLE_VISITANTE]
        ROLE_OPERADOR_PROPIO: [ROLE_OPERADOR_EXTERNO, ROLE_OPERADOR_EXTERNO_PRUEBAS, ROLE_VISITANTE]
        ROLE_ADMIN: [ROLE_OPERADOR_PROPIO, ROLE_OPERADOR_EXTERNO, ROLE_OPERADOR_EXTERNO_PRUEBAS, ROLE_VISITANTE, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: usuario

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_home
            logout:
                path: app_logout
                target: app_login

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/usuario/perfil, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/usuario, roles: ROLE_ADMIN }
        - { path: ^/especie, roles: ROLE_ADMIN }
        - { path: ^/ejemplar/eliminar, roles: ROLE_ADMIN }
        - { path: ^/ejemplar/crear, roles: ROLE_OPERADOR_PROPIO }
        - { path: ^/ejemplar/editar, roles: ROLE_OPERADOR_EXTERNO }
        - { path: ^/ejemplar/[0-9]+/captura/eliminar, roles: ROLE_ADMIN }
        - { path: ^/ejemplar/[0-9]+/captura/crear, roles: ROLE_OPERADOR_EXTERNO_PRUEBAS }
        - { path: ^/ejemplar/[0-9]+/captura/editar, roles: ROLE_OPERADOR_EXTERNO_PRUEBAS }
        - { path: ^/ejemplar, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
