services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: base
    restart: unless-stopped
    user: "${PHP_USER}"
    volumes:
      - .:/var/www/html
    env_file:
      - .env.local
    environment:
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}?serverVersion=${DB_VERSION}&charset=utf8mb4"
      COMPOSER_HOME: /var/www/html/var/composer

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data:
